### ISSUE TITLE
mona Error executing main.py (cannot open shared object file)

### ISSUE THREAD

**Issue by digitalw** [Francesco17/LTLf2DFA#2]
Hi, I was trying to get your library running and encountered the following error after a frech git clone:
```
./mona: error while loading shared libraries: libmonamem.so.1: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/bwright/.local/lib/python3.5/site-packages/dot_parser.py", line 548, in parse_dot_data
    tokens = graphparser.parseString(s)
  File "/home/bwright/.local/lib/python3.5/site-packages/pyparsing.py", line 1632, in parseString
    raise exc
  File "/home/bwright/.local/lib/python3.5/site-packages/pyparsing.py", line 1622, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/home/bwright/.local/lib/python3.5/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/bwright/.local/lib/python3.5/site-packages/pyparsing.py", line 3848, in parseImpl
    loc, tokens = self_expr_parse( instring, loc, doActions, callPreParse=False )
  File "/home/bwright/.local/lib/python3.5/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/bwright/.local/lib/python3.5/site-packages/pyparsing.py", line 3395, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/home/bwright/.local/lib/python3.5/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/bwright/.local/lib/python3.5/site-packages/pyparsing.py", line 3717, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/home/bwright/.local/lib/python3.5/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/bwright/.local/lib/python3.5/site-packages/pyparsing.py", line 3545, in parseImpl
    raise maxException
  File "/home/bwright/.local/lib/python3.5/site-packages/pyparsing.py", line 3530, in parseImpl
    ret = e._parse( instring, loc, doActions )
  File "/home/bwright/.local/lib/python3.5/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/bwright/.local/lib/python3.5/site-packages/pyparsing.py", line 2503, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pyparsing.ParseException: Expected {'graph' | 'digraph'} (at char 0), (line:1, col:1)
```

Anything required for mona? If so a mention on the requirements page would be great. Thanks for the support.

**Comment by digitalw** [comment]
Hi,
I was able to solve this by recompiling mona with the following parameters `/configure --enable-static --enable-shared=no`
